### PR TITLE
valve mount

### PR DESCRIPTION
**Pull request by generationmake**
mount for pressure sensor

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @generationmake :coffee: :wave: 

Thank you very much for this contribution :bow: 

I've attached a ZIP file containing a STL of the sensor for validation. Could you please check and let me know if sensor/mount fit?

[136884631-21-7975015.zip](https://github.com/107-systems/l3xz-cad/files/11417492/136884631-21-7975015.zip)

**Comment by generationmake** [comment]
stl is fine, but step would be better:

Screenshot from 2023-05-08 12-28-23

**Comment by aentinger** [comment]
Roger that, here are a couple of STEP files (there were 3 different versions to be exported):

[136899438-3-7975015.zip](https://github.com/107-systems/l3xz-cad/files/11420606/136899438-3-7975015.zip)
[136899452-19-7975015.zip](https://github.com/107-systems/l3xz-cad/files/11420607/136899452-19-7975015.zip)
[136899459-659-7975015.zip](https://github.com/107-systems/l3xz-cad/files/11420608/136899459-659-7975015.zip)

**Comment by aentinger** [comment]
Looking good 👍 

Do I understand correctly that printing valve_mount.stl two times forms the complete mount?

**Comment by aentinger** [comment]
Forgot image...

IMG_20230509_052256_194

**Review by aentinger — APPROVED** [review]
Lgtm 👍

**Pull request merged**
